import { Material, MaterialHistoryEvent, MaterialLocation } from '../types/material.types';

const now = new Date();

function isoDaysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function isoHoursAgo(hours: number): string {
  const d = new Date(now);
  d.setHours(d.getHours() - hours);
  return d.toISOString();
}

export const FLUX_TYPE_3_PART_NUMBERS = new Set(['PCB-4471-A', 'PCB-9902-C']);

const LINE_3_MACHINE_A_SLOT_12: MaterialLocation = {
  lineId: 'LINE-3',
  lineName: 'SMT Line 3',
  machineId: 'LINE-3-MC-A',
  machineName: 'Machine A',
  feederId: 'LINE-3-MC-A-SLOT-12',
  feederLabel: 'Slot 12',
};

export const HISTORY_SEED: Record<string, MaterialHistoryEvent[]> = {
  'MAT-1001': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(6), location: 'Warehouse A / Rack 12', operator: 'Andi P.' },
    { id: 'H-2', type: 'MC_DRY_OUT', timestamp: isoDaysAgo(3), location: 'MC Dry Cabinet 02', operator: 'Sari W.' },
    { id: 'H-3', type: 'MC_DRY_IN', timestamp: isoDaysAgo(4), location: 'MC Dry Cabinet 02', operator: 'Sari W.' },
  ],
  'MAT-1002': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(2), location: 'Warehouse B / Rack 04', operator: 'Budi S.' },
  ],
  'MAT-1003': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(20), location: 'Warehouse A / Rack 03', operator: 'Andi P.' },
    { id: 'H-2', type: 'BAKING_START', timestamp: isoDaysAgo(10), location: 'Baking Oven 1', operator: 'Rina T.' },
    { id: 'H-3', type: 'BAKING_COMPLETE', timestamp: isoDaysAgo(9), location: 'Baking Oven 1', operator: 'Rina T.' },
  ],
  'MAT-1004': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(1), location: 'Warehouse A / Rack 08', operator: 'Dedi K.' },
  ],
  'MAT-1005': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(15), location: 'Warehouse A / Rack 21', operator: 'Andi P.' },
    {
      id: 'H-2',
      type: 'STOCK_OUT',
      timestamp: isoDaysAgo(1),
      location: 'SMT Line 3 / Machine A / Slot 12',
      operator: 'Dedi K.',
    },
  ],
};

export const MATERIAL_SEED: Material[] = [
  {
    id: 'MAT-1001',
    qrCode: 'PCB-4471-A;L2201;112606130101',
    uniqueNumber: '112606130101',
    partNumber: 'PCB-4471-A',
    partName: 'Main Control PCB Rev.C',
    lotNumber: 'L2201',
    maker: 'Panasonic',
    supplier: 'PT Sinar Elektronika',
    manufacturingDate: isoDaysAgo(40),
    category: 'PCB',
    packageType: 'BOX',
    quantity: 250,
    unit: 'pcs',
    mslRank: 'MSL-3',
    colorRank: 'GREEN',
    luminousRank: 'N/A',
    shelfLifeDays: 365,
    exposureLimitHours: 0,
    openPackageDate: isoDaysAgo(4),
    accumulatedExposureHours: 0,
    exposureResumedAt: null,
    currentExposureHours: 0,
    bakingCount: 0,
    bakingLimit: 0,
    bakingAllowed: false,
    currentStatus: 'AVAILABLE',
    currentLocation: 'Warehouse A / Rack 12',
    storage: 'Rack 12',
    warehouse: 'Warehouse A',
    location: null,
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1001'],
  },
  {
    id: 'MAT-1002',
    qrCode: 'IC-8820-REEL;L0099;112606130102',
    uniqueNumber: '112606130102',
    partNumber: 'IC-8820-REEL',
    partName: 'ADC 12-bit SOIC-16',
    lotNumber: 'L0099',
    maker: 'Denso',
    supplier: 'Toyota Tsusho Electronics',
    manufacturingDate: isoDaysAgo(30),
    category: 'IC_REEL',
    packageType: 'REEL',
    quantity: 5000,
    unit: 'pcs',
    mslRank: 'MSL-2A',
    colorRank: 'YELLOW',
    luminousRank: 'B',
    shelfLifeDays: 0,
    exposureLimitHours: 168, // 7 days — still vacuum-sealed, so exposure hasn't started
    openPackageDate: null,
    accumulatedExposureHours: 0,
    exposureResumedAt: null,
    currentExposureHours: 0,
    bakingCount: 0,
    bakingLimit: 3,
    bakingAllowed: true,
    currentStatus: 'AVAILABLE',
    currentLocation: 'Warehouse B / Rack 04',
    storage: 'Rack 04',
    warehouse: 'Warehouse B',
    location: null,
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1002'],
  },
  {
    id: 'MAT-1003',
    qrCode: 'IC-3315-TRAY;L5541;112606130103',
    uniqueNumber: '112606130103',
    partNumber: 'IC-3315-TRAY',
    partName: 'Power MOSFET QFN-32',
    lotNumber: 'L5541',
    maker: 'Bosch',
    supplier: 'PT Komponen Presisi',
    manufacturingDate: isoDaysAgo(60),
    category: 'IC_TRAY',
    packageType: 'TRAY',
    quantity: 1200,
    unit: 'pcs',
    mslRank: 'MSL-4',
    colorRank: 'RED',
    luminousRank: 'C',
    shelfLifeDays: 0,
    exposureLimitHours: 96, // 4 days
    openPackageDate: isoHoursAgo(90),
    accumulatedExposureHours: 90, // WARNING zone: near the 96h limit, not baked yet
    exposureResumedAt: isoHoursAgo(90),
    currentExposureHours: 90,
    bakingCount: 1,
    bakingLimit: 3,
    bakingAllowed: true,
    currentStatus: 'IN_PRODUCTION',
    currentLocation: 'SMT Line 2 / Machine B / Slot 5',
    storage: '—',
    warehouse: 'Warehouse A',
    location: {
      lineId: 'LINE-2',
      lineName: 'SMT Line 2',
      machineId: 'LINE-2-MC-B',
      machineName: 'Machine B',
      feederId: 'LINE-2-MC-B-SLOT-5',
      feederLabel: 'Slot 5',
    },
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1003'],
  },
  {
    id: 'MAT-1004',
    qrCode: 'IC-9012-REEL;L6602;112606130104',
    uniqueNumber: '112606130104',
    partNumber: 'IC-9012-REEL',
    partName: 'Gate Driver SO-8',
    lotNumber: 'L6602',
    maker: 'Siemens',
    supplier: 'PT Sinar Elektronika',
    manufacturingDate: isoDaysAgo(10),
    category: 'IC_REEL',
    packageType: 'REEL',
    quantity: 8000,
    unit: 'pcs',
    mslRank: 'MSL-2',
    colorRank: 'GREEN',
    luminousRank: 'A',
    shelfLifeDays: 0,
    exposureLimitHours: 200,
    openPackageDate: isoHoursAgo(200),
    accumulatedExposureHours: 200, // already hit the limit 3 times -> baking limit reached
    exposureResumedAt: null,
    currentExposureHours: 200,
    bakingCount: 3,
    bakingLimit: 3,
    bakingAllowed: true,
    currentStatus: 'MC_DRY',
    currentLocation: 'MC Dry Cabinet 01',
    storage: 'MC Dry Cabinet 01',
    warehouse: 'Warehouse A',
    location: null,
    isInMcDry: true,
    history: HISTORY_SEED['MAT-1004'],
  },
  {
    id: 'MAT-1005',
    qrCode: 'PCB-9902-C;L7710;112606130105',
    uniqueNumber: '112606130105',
    partNumber: 'PCB-9902-C',
    partName: 'Sensor Interface PCB Rev.B',
    lotNumber: 'L7710',
    maker: 'Toyota',
    supplier: 'PT Komponen Presisi',
    manufacturingDate: isoDaysAgo(200),
    category: 'PCB',
    packageType: 'BOX',
    quantity: 60,
    unit: 'pcs',
    mslRank: 'MSL-3',
    colorRank: 'GREEN',
    luminousRank: 'N/A',
    shelfLifeDays: 240,
    exposureLimitHours: 0,
    openPackageDate: isoDaysAgo(55),
    accumulatedExposureHours: 0,
    exposureResumedAt: null,
    currentExposureHours: 0,
    bakingCount: 0,
    bakingLimit: 0,
    bakingAllowed: false,
    currentStatus: 'IN_PRODUCTION',
    currentLocation: 'SMT Line 3 / Machine A / Slot 12',
    storage: '—',
    warehouse: 'Warehouse A',
    location: LINE_3_MACHINE_A_SLOT_12,
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1005'],
  },
  {
    id: 'MAT-1006',
    qrCode: 'IC-5541-TRAY;L8801;112606130106',
    uniqueNumber: '112606130106',
    partNumber: 'IC-5541-TRAY',
    partName: 'RF Switch QFN-20',
    lotNumber: 'L8801',
    maker: 'Denso',
    supplier: 'PT Komponen Presisi',
    manufacturingDate: isoDaysAgo(12),
    category: 'IC_TRAY',
    packageType: 'TRAY',
    quantity: 900,
    unit: 'pcs',
    mslRank: 'MSL-5',
    colorRank: 'RED',
    luminousRank: 'D',
    shelfLifeDays: 0,
    exposureLimitHours: 48,
    openPackageDate: isoHoursAgo(52),
    accumulatedExposureHours: 52, // over the limit -> NEED BAKING
    exposureResumedAt: isoHoursAgo(52),
    currentExposureHours: 52,
    bakingCount: 0,
    bakingLimit: 2,
    bakingAllowed: true,
    currentStatus: 'IN_PRODUCTION',
    currentLocation: 'SMT Line 4 / Machine A / Slot 3',
    storage: '—',
    warehouse: 'Warehouse A',
    location: {
      lineId: 'LINE-4',
      lineName: 'SMT Line 4',
      machineId: 'LINE-4-MC-A',
      machineName: 'Machine A',
      feederId: 'LINE-4-MC-A-SLOT-3',
      feederLabel: 'Slot 3',
    },
    isInMcDry: false,
    history: [
      { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(12), location: 'Warehouse A / Rack 09', operator: 'Sari W.' },
      {
        id: 'H-2',
        type: 'STOCK_OUT',
        timestamp: isoHoursAgo(52),
        location: 'SMT Line 4 / Machine A / Slot 3',
        operator: 'Sari W.',
      },
    ],
  },
  {
    id: 'MAT-1007',
    // Matches the physical barcode label: JK949628-3630;Q42A51BECD1720F2;112604180010
    qrCode: 'JK949628-3630;Q42A51BECD1720F2;112604180010',
    uniqueNumber: '112604180010',
    partNumber: 'JK949628-3630',
    partName: 'Connector Housing IC REEL',
    lotNumber: 'Q42A51BECD1720F2',
    maker: 'Denso',
    supplier: 'Toyota Tsusho Electronics',
    manufacturingDate: isoDaysAgo(5),
    category: 'IC_REEL',
    packageType: 'REEL',
    quantity: 4000,
    unit: 'pcs',
    mslRank: 'MSL-3',
    colorRank: 'YELLOW',
    luminousRank: 'B',
    shelfLifeDays: 0,
    exposureLimitHours: 168, // MSL-3 -> 168h, still vacuum-sealed so exposure hasn't started
    openPackageDate: null,
    accumulatedExposureHours: 0,
    exposureResumedAt: null,
    currentExposureHours: 0,
    bakingCount: 0,
    bakingLimit: 3,
    bakingAllowed: true,
    currentStatus: 'AVAILABLE',
    currentLocation: 'Warehouse A / Rack 15',
    storage: 'Rack 15',
    warehouse: 'Warehouse A',
    location: null,
    isInMcDry: false,
    history: [
      {
        id: 'H-1',
        type: 'STOCK_IN',
        timestamp: isoDaysAgo(5),
        location: 'Warehouse A / Rack 15',
        operator: 'Dedi K.',
      },
    ],
  },
];

export const MASTER_DATA_NOT_FOUND_QR = new Set(['UNKNOWN-PART-0000;L0000;000000000000']);
