import { Material, MaterialHistoryEvent } from '../types/material.types';

const now = new Date();

function isoDaysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function isoHoursAgo(hours: number): string {
  const d = new Date(now);
  d.setHours(d.getHours() - hours);
  return d.toISOString();
}

export const FLUX_TYPE_3_PART_NUMBERS = new Set(['PCB-4471-A', 'PCB-9902-C']);

export const HISTORY_SEED: Record<string, MaterialHistoryEvent[]> = {
  'MAT-1001': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(6), location: 'Warehouse A / Rack 12', operator: 'Andi P.' },
    { id: 'H-2', type: 'MC_DRY_OUT', timestamp: isoDaysAgo(3), location: 'MC Dry Cabinet 02', operator: 'Sari W.' },
    { id: 'H-3', type: 'MC_DRY_IN', timestamp: isoDaysAgo(4), location: 'MC Dry Cabinet 02', operator: 'Sari W.' },
  ],
  'MAT-1002': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(2), location: 'Warehouse B / Rack 04', operator: 'Budi S.' },
  ],
  'MAT-1003': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(20), location: 'Warehouse A / Rack 03', operator: 'Andi P.' },
    { id: 'H-2', type: 'BAKING_START', timestamp: isoDaysAgo(10), location: 'Baking Oven 1', operator: 'Rina T.' },
    { id: 'H-3', type: 'BAKING_COMPLETE', timestamp: isoDaysAgo(9), location: 'Baking Oven 1', operator: 'Rina T.' },
  ],
  'MAT-1004': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(1), location: 'Warehouse A / Rack 08', operator: 'Dedi K.' },
  ],
  'MAT-1005': [
    { id: 'H-1', type: 'STOCK_IN', timestamp: isoDaysAgo(15), location: 'Line 3 Buffer', operator: 'Andi P.' },
    { id: 'H-2', type: 'STOCK_OUT', timestamp: isoDaysAgo(1), location: 'Line 3', operator: 'Dedi K.' },
  ],
};

export const MATERIAL_SEED: Material[] = [
  {
    id: 'MAT-1001',
    qrCode: 'QR-PCB-4471-A-L2201',
    partNumber: 'PCB-4471-A',
    partName: 'Main Control PCB Rev.C',
    lotNumber: 'L2201',
    maker: 'Panasonic',
    supplier: 'PT Sinar Elektronika',
    manufacturingDate: isoDaysAgo(40),
    category: 'PCB',
    packageType: 'BOX',
    quantity: 250,
    unit: 'pcs',
    mslRank: 'MSL-3',
    colorRank: 'GREEN',
    luminousRank: 'N/A',
    shelfLifeDays: 365,
    exposureLimitHours: 0,
    openPackageDate: isoDaysAgo(4),
    currentExposureHours: 0,
    bakingCount: 0,
    bakingLimit: 3,
    currentStatus: 'AVAILABLE',
    currentLocation: 'Warehouse A / Rack 12',
    storage: 'Rack 12',
    warehouse: 'Warehouse A',
    line: null,
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1001'],
  },
  {
    id: 'MAT-1002',
    qrCode: 'QR-IC-REEL-8820-L0099',
    partNumber: 'IC-8820-REEL',
    partName: 'ADC 12-bit SOIC-16',
    lotNumber: 'L0099',
    maker: 'Denso',
    supplier: 'Toyota Tsusho Electronics',
    manufacturingDate: isoDaysAgo(30),
    category: 'IC_REEL',
    packageType: 'REEL',
    quantity: 5000,
    unit: 'pcs',
    mslRank: 'MSL-2A',
    colorRank: 'YELLOW',
    luminousRank: 'B',
    shelfLifeDays: 0,
    exposureLimitHours: 168, // 7 days
    openPackageDate: isoHoursAgo(20),
    currentExposureHours: 20,
    bakingCount: 0,
    bakingLimit: 3,
    currentStatus: 'AVAILABLE',
    currentLocation: 'Warehouse B / Rack 04',
    storage: 'Rack 04',
    warehouse: 'Warehouse B',
    line: null,
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1002'],
  },
  {
    id: 'MAT-1003',
    qrCode: 'QR-IC-TRAY-3315-L5541',
    partNumber: 'IC-3315-TRAY',
    partName: 'Power MOSFET QFN-32',
    lotNumber: 'L5541',
    maker: 'Bosch',
    supplier: 'PT Komponen Presisi',
    manufacturingDate: isoDaysAgo(60),
    category: 'IC_TRAY',
    packageType: 'TRAY',
    quantity: 1200,
    unit: 'pcs',
    mslRank: 'MSL-4',
    colorRank: 'RED',
    luminousRank: 'C',
    shelfLifeDays: 0,
    exposureLimitHours: 96, // 4 days
    openPackageDate: isoHoursAgo(110),
    currentExposureHours: 96,
    bakingCount: 1,
    bakingLimit: 3,
    currentStatus: 'AVAILABLE',
    currentLocation: 'Warehouse A / Rack 03',
    storage: 'Rack 03',
    warehouse: 'Warehouse A',
    line: null,
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1003'],
  },
  {
    id: 'MAT-1004',
    qrCode: 'QR-IC-REEL-9012-L6602',
    partNumber: 'IC-9012-REEL',
    partName: 'Gate Driver SO-8',
    lotNumber: 'L6602',
    maker: 'Siemens',
    supplier: 'PT Sinar Elektronika',
    manufacturingDate: isoDaysAgo(10),
    category: 'IC_REEL',
    packageType: 'REEL',
    quantity: 8000,
    unit: 'pcs',
    mslRank: 'MSL-2',
    colorRank: 'GREEN',
    luminousRank: 'A',
    shelfLifeDays: 0,
    exposureLimitHours: 200,
    openPackageDate: isoHoursAgo(30),
    currentExposureHours: 30,
    bakingCount: 3,
    bakingLimit: 3,
    currentStatus: 'MC_DRY',
    currentLocation: 'MC Dry Cabinet 01',
    storage: 'MC Dry Cabinet 01',
    warehouse: 'Warehouse A',
    line: null,
    isInMcDry: true,
    history: HISTORY_SEED['MAT-1004'],
  },
  {
    id: 'MAT-1005',
    qrCode: 'QR-PCB-9902-C-L7710',
    partNumber: 'PCB-9902-C',
    partName: 'Sensor Interface PCB Rev.B',
    lotNumber: 'L7710',
    maker: 'Toyota',
    supplier: 'PT Komponen Presisi',
    manufacturingDate: isoDaysAgo(200),
    category: 'PCB',
    packageType: 'BOX',
    quantity: 60,
    unit: 'pcs',
    mslRank: 'MSL-3',
    colorRank: 'GREEN',
    luminousRank: 'N/A',
    shelfLifeDays: 240,
    exposureLimitHours: 0,
    openPackageDate: isoDaysAgo(55),
    currentExposureHours: 0,
    bakingCount: 0,
    bakingLimit: 3,
    currentStatus: 'STOCK_OUT',
    currentLocation: 'Line 3',
    storage: '—',
    warehouse: 'Warehouse A',
    line: 'Line 3',
    isInMcDry: false,
    history: HISTORY_SEED['MAT-1005'],
  },
];

export const MASTER_DATA_NOT_FOUND_QR = new Set(['QR-UNKNOWN-0000-L0000']);
