
export const PCB_FLUX_TYPE_3_OPEN_SHELF_LIFE_DAYS = 60;

export const SHELF_LIFE_NEAR_EXPIRY_THRESHOLD_DAYS = 7;

export const EXPOSURE_WARNING_THRESHOLD_PERCENT = 80;

export const DEFAULT_BAKING_LIMIT = 3;
